In [ ]:
#numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

print(type(a))
print(a.shape)
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


In [ ]:
c = np.zeros((2,2))
print(c)

d = np.ones((2,2))
print(d)

e = np.full((2,2), 6)
print(e)

f = np.eye(3)
print(f)

g = np.random.randint(1, 11, size = (3,3))
print(g)

h = np.arange(7)
print(h)

i = np.random.random((3,3))
print(i)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[6 6]
 [6 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 4  7  2]
 [ 1  7 10]
 [10  8  2]]
[0 1 2 3 4 5 6]
[[0.7775654  0.95673056 0.6103984 ]
 [0.53213545 0.72225723 0.2149691 ]
 [0.99809869 0.38128964 0.06457096]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4]) #end-value is never included.

[2 3 4]


In [ ]:
a = [0,1,2,3]
a = np.append(a, [1,2,3,4])
print(a)

[0 1 2 3 1 2 3 4]


In [ ]:
a = np.delete(a, [2,4]) #[2,4] is not a range, these are the only two elements (indicies) getting deleted.
print(a)

[0 1 2 4]


In [ ]:
arr = np.arange(24)
newarr = arr.reshape(6,4)
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#scipy

In [ ]:
from scipy.optimize import root
from math import cos

def eqn(x):
  return x + np.cos(x)

myroot = root(eqn , 0)
print(myroot.x[0])


-0.7390851332151607


In [ ]:
from scipy.interpolate import interp1d
import numpy as np

xs = np.arange(10)
ys = 2*xs + 1
print(xs)
print(ys)

interp_func = interp1d(xs, ys)
newarr = interp_func(np.arange(2.1, 3, 0.1))
print(newarr)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8]


In [ ]:
#panda

In [ ]:
import pandas as pd
series = pd.Series([1,2,3,4, 'data value'])
print(series)

0             1
1             2
2             3
3             4
4    data value
dtype: object


In [ ]:
import pandas as pd
series = pd.Series([1,2,3,4,'data value'], index = ['a', 'b', 'c', 'd', 'e'])
print(series)

a             1
b             2
c             3
d             4
e    data value
dtype: object


In [ ]:
import pandas as pd
series = pd.Series([1,2,3,4], index = ['a','b','c', 'd'], dtype = float)
print(series)

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64


In [ ]:
s_1 = pd.Series([1,2,3,4,5])
s_2 = pd.Series([10,20,30,40,50])
s_3 = s_1 + s_2
print(s_3)

0    11
1    22
2    33
3    44
4    55
dtype: int64


In [ ]:
import pandas as pd
data = [
    ['Akshay', 20, 'Bhopal'],
    ['Rohit', 19, 'Faridabad'],
    ['Yash', 19, 'Pune'],
    ['Rohit K', 20, 'Beyawar']
]

df = pd.DataFrame(data, columns = ['Name', 'Age', 'City'])
display(df)

,Name,Age,City
0,Akshay,20,Bhopal
1,Rohit,19,Faridabad
2,Yash,19,Pune
3,Rohit K,20,Beyawar


In [ ]:
print(df.shape)
print(df.columns)
print(df.info)

(4, 3)
Index(['Name', 'Age', 'City'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None
            Age
count   4.00000
mean   19.50000
std     0.57735
min    19.00000
25%    19.00000
50%    19.50000
75%    20.00000
max    20.00000


In [ ]:
A = np.arange(24)
print(A)
print(" ")


B = arr.reshape(2,3,4)
print(B)
print(" ")

temp = B[1::]
C = temp[:, :, 1::2]
print(C)
print(" ")


D = C.flatten()
print(D)
print(" ")

with np.nditer(D, op_flags=['readwrite']) as it:
  for x in it:
    if(x%3 == 0):
      x[...] = -1

    elif(x%5 == 0):
      x[...] = -2


E = D.reshape((3,2))
print(E)
print(" ")
E = E[1:, :-1]
print(E)
print(" ")
E = np.insert(E, 1, new_col, axis = 1)
print(E)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
 
[[[13 15]
  [17 19]
  [21 23]]]
 
[13 15 17 19 21 23]
 
[[13 -1]
 [17 19]
 [-1 23]]
 
[[17]
 [-1]]
 
[[17  1]
 [-1  1]]
